obj-m += cma_dma_pl.o

# PWD := $(shell pwd)
# CURDIR ?= $(PWD)
# TARGET ?= cma_dma_pl

# KDIR ?= /lib/modules/$(shell uname -r)/build

# CROSS_COMPILE ?= arm-linux-gnueabihf-
# ARCH ?= arm

# obj-m += $(TARGET).o

# all: $(TARGET).ko

# $(TARGET).ko: $(TARGET).c
# 	$(MAKE) -C $(KDIR) ARCH=$(ARCH) CROSS_COMPILE=$(CROSS_COMPILE) M=$(CURDIR) modules

# clean:
# 	@rm -fv *.symvers Module.symvers Module.markers modules.order
# 	@rm -rfv .tmp_versions
# 	@rm -fv *.ko *.mod* *.o .*.cmd
