UDEVMEM_VERSION = 0.0.1
UDEVMEM_SITE = $(BR2_EXTERNAL_CUSTOM_PACKAGE_PATH)/dl/udevmem
UDEVMEM_SITE_METHOD = local
# XILINX_VIRTUAL_CABLE_LICENSE = GPL-2.0+ 
# XILINX_VIRTUAL_CABLE_LICENSE_FILES = LICENSE 


define UDEVMEM_BUILD_CMDS
	$(MAKE) -C $(@D) CCC=$(TARGET_CC) all
endef


define UDEVMEM_INSTALL_TARGET_CMDS
	$(INSTALL) -D -m 0755 $(@D)/udevmem-0.0.1 $(TARGET_DIR)/usr/bin/udevmem
endef

$(eval $(generic-package))
