UDEVMEM_VERSION = v0.1.0
UDEVMEM_SITE = $(call github,Nayjl,udevmem,$(UDEVMEM_VERSION))

UDEVMEM_DEPENDENCIES = linux host-pkgconf
UDEVMEM_MAKE_ENV =

define UDEVMEM_BUILD_CMDS
	$(TARGET_MAKE_ENV) $(UDEVMEM_MAKE_ENV) $(MAKE) -C $(@D) \
		CC=$(TARGET_CC) \
		CFLAGS="$(TARGET_CFLAGS)" \
		CPPFLAGS="$(TARGET_CPPFLAGS)" \
		LDFLAGS="$(TARGET_LDFLAGS)" all
endef

define UDEVMEM_INSTALL_TARGET_CMDS
	$(TARGET_MAKE_ENV) $(UDEVMEM_MAKE_ENV) $(MAKE) -C $(@D) DESTDIR=$(TARGET_DIR) install
endef
# 	$(INSTALL) -D -m 0755 $(@D)/udevmem $(TARGET_DIR)/usr/bin/udevmem

# define UDEVMEM_INSTALL_STAGING_CMDS
# 	$(TARGET_MAKE_ENV) $(UDEVMEM_MAKE_ENV) $(MAKE) -C $(@D) DESTDIR=$(STAGING_DIR) install
# endef

$(eval $(generic-package))
