XADC_LNX_VERSION = v0.1.0
XADC_LNX_SITE = $(call github,Nayjl,xadc-lnx,$(XADC_LNX_VERSION))
# XILINX_VIRTUAL_CABLE_LICENSE = GPL-2.0+  
# XILINX_VIRTUAL_CABLE_LICENSE_FILES = LICENSE

XADC_LNX_DEPENDENCIES = linux host-pkgconf
XADC_LNX_MAKE_ENV =

# ifeq ($(strip $(PATH_IIO_XADC)),)

# else

# endif

XADC_CPPFLAGS += -D_XADC_IIO_PTH='\"$(BR2_PACKAGE_XADC_LNX_PTH_DEVICE)\"'

define XADC_LNX_BUILD_CMDS
	$(TARGET_MAKE_ENV) $(XADC_LNX_MAKE_ENV) $(MAKE) -C $(@D) \
		CC=$(TARGET_CC) \
		CFLAGS="$(TARGET_CFLAGS)" \
		CPPFLAGS="$(TARGET_CPPFLAGS) $(XADC_CPPFLAGS)" \
		LDFLAGS="$(TARGET_LDFLAGS)" all
endef

define XADC_LNX_INSTALL_TARGET_CMDS
	$(TARGET_MAKE_ENV) $(XADC_LNX_MAKE_ENV) $(MAKE) -C $(@D) DESTDIR=$(TARGET_DIR) install
endef

$(eval $(generic-package))
