

set_property -dict { PACKAGE_PIN    N11     IOSTANDARD  LVCMOS33    } [get_ports    SYS_CLK        ]
set_property -dict { PACKAGE_PIN    C8      IOSTANDARD  LVCMOS33    } [get_ports    BANK15_C8_LED  ]
set_property -dict { PACKAGE_PIN    A8      IOSTANDARD  LVCMOS33    } [get_ports    BANK15_A8_RESET]


# DDR
set_property -dict { PACKAGE_PIN    H12      IOSTANDARD  LVCMOS33    } [get_ports    D0     ]
set_property -dict { PACKAGE_PIN    H13      IOSTANDARD  LVCMOS33    } [get_ports    D1     ]
set_property -dict { PACKAGE_PIN    J15      IOSTANDARD  LVCMOS33    } [get_ports    D2     ]
set_property -dict { PACKAGE_PIN    H14      IOSTANDARD  LVCMOS33    } [get_ports    D3     ]
set_property -dict { PACKAGE_PIN    J16      IOSTANDARD  LVCMOS33    } [get_ports    D4     ]
set_property -dict { PACKAGE_PIN    H16      IOSTANDARD  LVCMOS33    } [get_ports    D5     ]
set_property -dict { PACKAGE_PIN    G14      IOSTANDARD  LVCMOS33    } [get_ports    D6     ]
set_property -dict { PACKAGE_PIN    G12      IOSTANDARD  LVCMOS33    } [get_ports    D7     ]
set_property -dict { PACKAGE_PIN    C16      IOSTANDARD  LVCMOS33    } [get_ports    D8     ]
set_property -dict { PACKAGE_PIN    D15      IOSTANDARD  LVCMOS33    } [get_ports    D9     ]
set_property -dict { PACKAGE_PIN    D16      IOSTANDARD  LVCMOS33    } [get_ports    D10     ]
set_property -dict { PACKAGE_PIN    E15      IOSTANDARD  LVCMOS33    } [get_ports    D11     ]
set_property -dict { PACKAGE_PIN    E16      IOSTANDARD  LVCMOS33    } [get_ports    D12     ]
set_property -dict { PACKAGE_PIN    F15      IOSTANDARD  LVCMOS33    } [get_ports    D13     ]
set_property -dict { PACKAGE_PIN    G15      IOSTANDARD  LVCMOS33    } [get_ports    D14     ]
set_property -dict { PACKAGE_PIN    G16      IOSTANDARD  LVCMOS33    } [get_ports    D15     ]



set_property -dict { PACKAGE_PIN    C13      IOSTANDARD  LVCMOS33    } [get_ports    A0     ]
set_property -dict { PACKAGE_PIN    A15      IOSTANDARD  LVCMOS33    } [get_ports    A1     ]
set_property -dict { PACKAGE_PIN    C12      IOSTANDARD  LVCMOS33    } [get_ports    A2     ]
set_property -dict { PACKAGE_PIN    C11      IOSTANDARD  LVCMOS33    } [get_ports    A3     ]
set_property -dict { PACKAGE_PIN    A9       IOSTANDARD  LVCMOS33    } [get_ports    A4     ]
set_property -dict { PACKAGE_PIN    B9       IOSTANDARD  LVCMOS33    } [get_ports    A5     ]
set_property -dict { PACKAGE_PIN    A10      IOSTANDARD  LVCMOS33    } [get_ports    A6     ]
set_property -dict { PACKAGE_PIN    B10      IOSTANDARD  LVCMOS33    } [get_ports    A7     ]
set_property -dict { PACKAGE_PIN    B11      IOSTANDARD  LVCMOS33    } [get_ports    A8     ]
set_property -dict { PACKAGE_PIN    A12      IOSTANDARD  LVCMOS33    } [get_ports    A9     ]
set_property -dict { PACKAGE_PIN    B15      IOSTANDARD  LVCMOS33    } [get_ports    A10     ]
set_property -dict { PACKAGE_PIN    B12      IOSTANDARD  LVCMOS33    } [get_ports    A11     ]
set_property -dict { PACKAGE_PIN    A13      IOSTANDARD  LVCMOS33    } [get_ports    A12     ]
set_property -dict { PACKAGE_PIN    D13      IOSTANDARD  LVCMOS33    } [get_ports    A13     ]
set_property -dict { PACKAGE_PIN    C14      IOSTANDARD  LVCMOS33    } [get_ports    A14     ]

set_property -dict { PACKAGE_PIN    A14      IOSTANDARD  LVCMOS33    } [get_ports    SDCKE0     ]
set_property -dict { PACKAGE_PIN    B14      IOSTANDARD  LVCMOS33    } [get_ports    SDCLK0     ]
set_property -dict { PACKAGE_PIN    F12      IOSTANDARD  LVCMOS33    } [get_ports    DQML       ]
set_property -dict { PACKAGE_PIN    B16      IOSTANDARD  LVCMOS33    } [get_ports    DQMH       ]
set_property -dict { PACKAGE_PIN    F13      IOSTANDARD  LVCMOS33    } [get_ports    CAS        ]
set_property -dict { PACKAGE_PIN    E13      IOSTANDARD  LVCMOS33    } [get_ports    RAS        ]
set_property -dict { PACKAGE_PIN    F14      IOSTANDARD  LVCMOS33    } [get_ports    SDWE       ]
set_property -dict { PACKAGE_PIN    D14      IOSTANDARD  LVCMOS33    } [get_ports    SD_NCS0    ]


# flash ram
set_property -dict { PACKAGE_PIN    J13      IOSTANDARD  LVCMOS33    } [get_ports    FPGA_DQ0       ]
set_property -dict { PACKAGE_PIN    j14      IOSTANDARD  LVCMOS33    } [get_ports    FPGA_DQ1       ]
set_property -dict { PACKAGE_PIN    k15      IOSTANDARD  LVCMOS33    } [get_ports    FPGA_DQ2        ]
set_property -dict { PACKAGE_PIN    k16      IOSTANDARD  LVCMOS33    } [get_ports    FPGA_DQ3        ]
set_property -dict { PACKAGE_PIN    E8       IOSTANDARD  LVCMOS33    } [get_ports    FPGA_CCLK     ]
set_property -dict { PACKAGE_PIN    L12      IOSTANDARD  LVCMOS33    } [get_ports    FPGA_CSO_B     ]



# u7
set_property -dict { PACKAGE_PIN    N13          IOSTANDARD  LVCMOS33    } [get_ports      BANK14_N13_8         ]
set_property -dict { PACKAGE_PIN    N16          IOSTANDARD  LVCMOS33    } [get_ports      BANK14_N16_10        ]
set_property -dict { PACKAGE_PIN    P15          IOSTANDARD  LVCMOS33    } [get_ports      BANK14_P15_12        ]
set_property -dict { PACKAGE_PIN    R16          IOSTANDARD  LVCMOS33    } [get_ports      BANK14_R16_14        ]
set_property -dict { PACKAGE_PIN    T15          IOSTANDARD  LVCMOS33    } [get_ports      BANK14_T15_16        ]
set_property -dict { PACKAGE_PIN    P14          IOSTANDARD  LVCMOS33    } [get_ports      BANK14_P14_18        ]
set_property -dict { PACKAGE_PIN    R13          IOSTANDARD  LVCMOS33    } [get_ports      BANK14_R13_20        ]
set_property -dict { PACKAGE_PIN    R12          IOSTANDARD  LVCMOS33    } [get_ports      BANK14_R12_22        ]
set_property -dict { PACKAGE_PIN    P13          IOSTANDARD  LVCMOS33    } [get_ports      BANK14_P13_24        ]
set_property -dict { PACKAGE_PIN    K13          IOSTANDARD  LVCMOS33    } [get_ports      BANK14_K13_26        ]
set_property -dict { PACKAGE_PIN    P11          IOSTANDARD  LVCMOS33    } [get_ports      BANK14_P11_28        ]
set_property -dict { PACKAGE_PIN    P9           IOSTANDARD  LVCMOS33    } [get_ports      BANK14_P9_30         ]
set_property -dict { PACKAGE_PIN    R11          IOSTANDARD  LVCMOS33    } [get_ports      BANK14_R11_32        ]
set_property -dict { PACKAGE_PIN    R10          IOSTANDARD  LVCMOS33    } [get_ports      BANK14_R10_34        ]
set_property -dict { PACKAGE_PIN    R8           IOSTANDARD  LVCMOS33    } [get_ports      BANK14_R8_36         ]
set_property -dict { PACKAGE_PIN    R7           IOSTANDARD  LVCMOS33    } [get_ports      BANK14_R7_38         ]
set_property -dict { PACKAGE_PIN    R6           IOSTANDARD  LVCMOS33    } [get_ports      BANK14_R6_40         ]
set_property -dict { PACKAGE_PIN    R5           IOSTANDARD  LVCMOS33    } [get_ports      BANK14_R5_42         ]
set_property -dict { PACKAGE_PIN    P6           IOSTANDARD  LVCMOS33    } [get_ports      BANK14_P6_44         ]

set_property -dict { PACKAGE_PIN    P5           IOSTANDARD  LVCMOS33    } [get_ports      BANK34_P5_46         ]
set_property -dict { PACKAGE_PIN    T3           IOSTANDARD  LVCMOS33    } [get_ports      BANK34_T3_48         ]
set_property -dict { PACKAGE_PIN    T2           IOSTANDARD  LVCMOS33    } [get_ports      BANK34_T2_50         ]
set_property -dict { PACKAGE_PIN    R1           IOSTANDARD  LVCMOS33    } [get_ports      BANK34_R1_52         ]
set_property -dict { PACKAGE_PIN    N4           IOSTANDARD  LVCMOS33    } [get_ports      BANK34_N4_54         ]
set_property -dict { PACKAGE_PIN    P3           IOSTANDARD  LVCMOS33    } [get_ports      BANK34_P3_56         ]
set_property -dict { PACKAGE_PIN    P1           IOSTANDARD  LVCMOS33    } [get_ports      BANK34_P1_58         ]
set_property -dict { PACKAGE_PIN    M1           IOSTANDARD  LVCMOS33    } [get_ports      BANK34_M1_60         ]




set_property -dict { PACKAGE_PIN    M16      IOSTANDARD  LVCMOS33    } [get_ports    BANK14_M16_7      ]
set_property -dict { PACKAGE_PIN    N14      IOSTANDARD  LVCMOS33    } [get_ports    BANK14_N14_9      ]
set_property -dict { PACKAGE_PIN    P16      IOSTANDARD  LVCMOS33    } [get_ports    BANK14_P16_11     ]
set_property -dict { PACKAGE_PIN    R15      IOSTANDARD  LVCMOS33    } [get_ports    BANK14_R15_13     ]
set_property -dict { PACKAGE_PIN    T14      IOSTANDARD  LVCMOS33    } [get_ports    BANK14_T14_15     ]
set_property -dict { PACKAGE_PIN    M12      IOSTANDARD  LVCMOS33    } [get_ports    BANK14_M12_17     ]
set_property -dict { PACKAGE_PIN    T13      IOSTANDARD  LVCMOS33    } [get_ports    BANK14_T13_19     ]
set_property -dict { PACKAGE_PIN    T12      IOSTANDARD  LVCMOS33    } [get_ports    BANK14_T12_21     ]
set_property -dict { PACKAGE_PIN    N12      IOSTANDARD  LVCMOS33    } [get_ports    BANK14_N12_23     ]
set_property -dict { PACKAGE_PIN    K12      IOSTANDARD  LVCMOS33    } [get_ports    BANK14_K12_25     ]
set_property -dict { PACKAGE_PIN    P10      IOSTANDARD  LVCMOS33    } [get_ports    BANK14_P10_27     ]
set_property -dict { PACKAGE_PIN    N9       IOSTANDARD  LVCMOS33    } [get_ports    BANK14_N9_29      ]
set_property -dict { PACKAGE_PIN    T10      IOSTANDARD  LVCMOS33    } [get_ports    BANK14_T10_31     ]
set_property -dict { PACKAGE_PIN    T9       IOSTANDARD  LVCMOS33    } [get_ports    BANK14_T9_33     ]
set_property -dict { PACKAGE_PIN    T8       IOSTANDARD  LVCMOS33    } [get_ports    BANK14_T8_35     ]
set_property -dict { PACKAGE_PIN    T7       IOSTANDARD  LVCMOS33    } [get_ports    BANK14_T7_37     ]
set_property -dict { PACKAGE_PIN    T5       IOSTANDARD  LVCMOS33    } [get_ports    BANK14_T5_39     ]
set_property -dict { PACKAGE_PIN    M6       IOSTANDARD  LVCMOS33    } [get_ports    BANK14_M6_41     ]
set_property -dict { PACKAGE_PIN    N6       IOSTANDARD  LVCMOS33    } [get_ports    BANK14_N6_43     ]

set_property -dict { PACKAGE_PIN    L5       IOSTANDARD  LVCMOS33    } [get_ports    BANK34_L5_45     ]
set_property -dict { PACKAGE_PIN    T4       IOSTANDARD  LVCMOS33    } [get_ports    BANK34_T4_47     ]
set_property -dict { PACKAGE_PIN    R3       IOSTANDARD  LVCMOS33    } [get_ports    BANK34_R3_49     ]
set_property -dict { PACKAGE_PIN    R2       IOSTANDARD  LVCMOS33    } [get_ports    BANK34_R2_51     ]
set_property -dict { PACKAGE_PIN    M5       IOSTANDARD  LVCMOS33    } [get_ports    BANK34_M5_53     ]
set_property -dict { PACKAGE_PIN    P4       IOSTANDARD  LVCMOS33    } [get_ports    BANK34_P4_55     ]
set_property -dict { PACKAGE_PIN    N1       IOSTANDARD  LVCMOS33    } [get_ports    BANK34_N1_57     ]
set_property -dict { PACKAGE_PIN    M2       IOSTANDARD  LVCMOS33    } [get_ports    BANK34_M2_59     ]





# u8
set_property -dict { PACKAGE_PIN     A7           IOSTANDARD  LVCMOS33    } [get_ports      BANK35_A7_8         ]
set_property -dict { PACKAGE_PIN     B5           IOSTANDARD  LVCMOS33    } [get_ports      BANK35_B5_10        ]
set_property -dict { PACKAGE_PIN     K5           IOSTANDARD  LVCMOS33    } [get_ports      BANK35_K5_12        ]
set_property -dict { PACKAGE_PIN     J4           IOSTANDARD  LVCMOS33    } [get_ports      BANK35_J4_14        ]
set_property -dict { PACKAGE_PIN     G4           IOSTANDARD  LVCMOS33    } [get_ports      BANK35_G4_16        ]
set_property -dict { PACKAGE_PIN     C6           IOSTANDARD  LVCMOS33    } [get_ports      BANK35_C6_18        ]
set_property -dict { PACKAGE_PIN     D5           IOSTANDARD  LVCMOS33    } [get_ports      BANK35_D5_20        ]
set_property -dict { PACKAGE_PIN     A4           IOSTANDARD  LVCMOS33    } [get_ports      BANK35_A4_22        ]
set_property -dict { PACKAGE_PIN     A3           IOSTANDARD  LVCMOS33    } [get_ports      BANK35_A3_24        ]
set_property -dict { PACKAGE_PIN     C4           IOSTANDARD  LVCMOS33    } [get_ports      BANK35_C4_26        ]
set_property -dict { PACKAGE_PIN     C2           IOSTANDARD  LVCMOS33    } [get_ports      BANK35_C2_28        ]
set_property -dict { PACKAGE_PIN     A2           IOSTANDARD  LVCMOS33    } [get_ports      BANK35_A2_30        ]
set_property -dict { PACKAGE_PIN     B1           IOSTANDARD  LVCMOS33    } [get_ports      BANK35_B1_32        ]
set_property -dict { PACKAGE_PIN     D1           IOSTANDARD  LVCMOS33    } [get_ports      BANK35_D1_34        ]
set_property -dict { PACKAGE_PIN     D3           IOSTANDARD  LVCMOS33    } [get_ports      BANK35_D3_36        ]
set_property -dict { PACKAGE_PIN     E5           IOSTANDARD  LVCMOS33    } [get_ports      BANK35_E5_38        ]
set_property -dict { PACKAGE_PIN     E1           IOSTANDARD  LVCMOS33    } [get_ports      BANK35_E1_40        ]
set_property -dict { PACKAGE_PIN     F3           IOSTANDARD  LVCMOS33    } [get_ports      BANK35_F3_42        ]
set_property -dict { PACKAGE_PIN     G1           IOSTANDARD  LVCMOS33    } [get_ports      BANK35_G1_44        ]

set_property -dict { PACKAGE_PIN     H1           IOSTANDARD  LVCMOS33    } [get_ports      BANK35_H1_46        ]
set_property -dict { PACKAGE_PIN     J1           IOSTANDARD  LVCMOS33    } [get_ports      BANK35_J1_48        ]
set_property -dict { PACKAGE_PIN     L2           IOSTANDARD  LVCMOS33    } [get_ports      BANK35_L2_50        ]
set_property -dict { PACKAGE_PIN     H4           IOSTANDARD  LVCMOS33    } [get_ports      BANK35_H4_52        ]
set_property -dict { PACKAGE_PIN     H3           IOSTANDARD  LVCMOS33    } [get_ports      BANK35_H3_54        ]
set_property -dict { PACKAGE_PIN     K2           IOSTANDARD  LVCMOS33    } [get_ports      BANK35_K2_56        ]
set_property -dict { PACKAGE_PIN     M4           IOSTANDARD  LVCMOS33    } [get_ports      BANK34_M4_58        ]
set_property -dict { PACKAGE_PIN     N2           IOSTANDARD  LVCMOS33    } [get_ports      BANK34_N2_60        ]





set_property -dict { PACKAGE_PIN    B7      IOSTANDARD  LVCMOS33    } [get_ports    BANK35_B7_7      ]
set_property -dict { PACKAGE_PIN    B6      IOSTANDARD  LVCMOS33    } [get_ports    BANK35_B6_9      ]
set_property -dict { PACKAGE_PIN    E6      IOSTANDARD  LVCMOS33    } [get_ports    BANK35_E6_11     ]
set_property -dict { PACKAGE_PIN    J5      IOSTANDARD  LVCMOS33    } [get_ports    BANK35_J5_13     ]
set_property -dict { PACKAGE_PIN    G5      IOSTANDARD  LVCMOS33    } [get_ports    BANK35_G5_15     ]
set_property -dict { PACKAGE_PIN    C7      IOSTANDARD  LVCMOS33    } [get_ports    BANK35_C7_17     ]
set_property -dict { PACKAGE_PIN    D6      IOSTANDARD  LVCMOS33    } [get_ports    BANK35_D6_19     ]
set_property -dict { PACKAGE_PIN    A5      IOSTANDARD  LVCMOS33    } [get_ports    BANK35_A5_21     ]
set_property -dict { PACKAGE_PIN    B4      IOSTANDARD  LVCMOS33    } [get_ports    BANK35_B4_23     ]
set_property -dict { PACKAGE_PIN    D4      IOSTANDARD  LVCMOS33    } [get_ports    BANK35_D4_25     ]
set_property -dict { PACKAGE_PIN    C3      IOSTANDARD  LVCMOS33    } [get_ports    BANK35_C3_27     ]
set_property -dict { PACKAGE_PIN    B2      IOSTANDARD  LVCMOS33    } [get_ports    BANK35_B2_29     ]
set_property -dict { PACKAGE_PIN    C1      IOSTANDARD  LVCMOS33    } [get_ports    BANK35_C1_31     ]
set_property -dict { PACKAGE_PIN    E2      IOSTANDARD  LVCMOS33    } [get_ports    BANK35_E2_33     ]
set_property -dict { PACKAGE_PIN    E3      IOSTANDARD  LVCMOS33    } [get_ports    BANK35_E3_35     ]
set_property -dict { PACKAGE_PIN    F5      IOSTANDARD  LVCMOS33    } [get_ports    BANK35_F5_37     ]
set_property -dict { PACKAGE_PIN    F2      IOSTANDARD  LVCMOS33    } [get_ports    BANK35_F2_39     ]
set_property -dict { PACKAGE_PIN    F4      IOSTANDARD  LVCMOS33    } [get_ports    BANK35_F4_41     ]
set_property -dict { PACKAGE_PIN    G2      IOSTANDARD  LVCMOS33    } [get_ports    BANK35_G2_43     ]

set_property -dict { PACKAGE_PIN    H2      IOSTANDARD  LVCMOS33    } [get_ports    BANK35_H2_45     ]
set_property -dict { PACKAGE_PIN    K1      IOSTANDARD  LVCMOS33    } [get_ports    BANK35_K1_47     ]
set_property -dict { PACKAGE_PIN    L3      IOSTANDARD  LVCMOS33    } [get_ports    BANK35_L3_49     ]
set_property -dict { PACKAGE_PIN    H5      IOSTANDARD  LVCMOS33    } [get_ports    BANK35_H5_51     ]
set_property -dict { PACKAGE_PIN    J3      IOSTANDARD  LVCMOS33    } [get_ports    BANK35_J3_53     ]
set_property -dict { PACKAGE_PIN    K3      IOSTANDARD  LVCMOS33    } [get_ports    BANK35_K3_55     ]
set_property -dict { PACKAGE_PIN    L4      IOSTANDARD  LVCMOS33    } [get_ports    BANK34_L4_57     ]
set_property -dict { PACKAGE_PIN    N3      IOSTANDARD  LVCMOS33    } [get_ports    BANK34_N3_59     ]










# Diff
# set_property -dict { PACKAGE_PIN    M16      IOSTANDARD  LVDS    } [get_ports    BANK14_M16_P      ]
# set_property -dict { PACKAGE_PIN    N16      IOSTANDARD  LVDS    } [get_ports    BANK14_N16_N      ]
# set_property -dict { PACKAGE_PIN    P16      IOSTANDARD  LVDS    } [get_ports    BANK14_P16_P     ]
# set_property -dict { PACKAGE_PIN    P15      IOSTANDARD  LVDS    } [get_ports    BANK14_P15_N     ]
# set_property -dict { PACKAGE_PIN    R15      IOSTANDARD  LVDS    } [get_ports    BANK14_R15_P     ]
# set_property -dict { PACKAGE_PIN    R16      IOSTANDARD  LVDS    } [get_ports    BANK14_R16_N     ]
# set_property -dict { PACKAGE_PIN    T14      IOSTANDARD  LVDS    } [get_ports    BANK14_T14_P     ]
# set_property -dict { PACKAGE_PIN    T15      IOSTANDARD  LVDS    } [get_ports    BANK14_T15_N     ]
# set_property -dict { PACKAGE_PIN    N13      IOSTANDARD  LVDS    } [get_ports    BANK14_N13_P     ]
# set_property -dict { PACKAGE_PIN    P13      IOSTANDARD  LVDS    } [get_ports    BANK14_P13_N     ]
# set_property -dict { PACKAGE_PIN    N14      IOSTANDARD  LVDS    } [get_ports    BANK14_N14_P     ]
# set_property -dict { PACKAGE_PIN    P14      IOSTANDARD  LVDS    } [get_ports    BANK14_P14_N     ]
# set_property -dict { PACKAGE_PIN    P10      IOSTANDARD  LVDS    } [get_ports    BANK14_P10_P     ]
# set_property -dict { PACKAGE_PIN    P11      IOSTANDARD  LVDS    } [get_ports    BANK14_P11_N     ]
# set_property -dict { PACKAGE_PIN    R12      IOSTANDARD  LVDS    } [get_ports    BANK14_R12_P     ]
# set_property -dict { PACKAGE_PIN    T12      IOSTANDARD  LVDS    } [get_ports    BANK14_T12_N     ]
# set_property -dict { PACKAGE_PIN    R13      IOSTANDARD  LVDS    } [get_ports    BANK14_R13_P     ]
# set_property -dict { PACKAGE_PIN    T13      IOSTANDARD  LVDS    } [get_ports    BANK14_T13_N     ]
# set_property -dict { PACKAGE_PIN    R10      IOSTANDARD  LVDS    } [get_ports    BANK14_R10_P     ]
# set_property -dict { PACKAGE_PIN    R11      IOSTANDARD  LVDS    } [get_ports    BANK14_R11_N     ]
# set_property -dict { PACKAGE_PIN    N9       IOSTANDARD  LVDS    } [get_ports    BANK14_N9_P     ]
# set_property -dict { PACKAGE_PIN    P9       IOSTANDARD  LVDS    } [get_ports    BANK14_P9_N     ]
# set_property -dict { PACKAGE_PIN    M6       IOSTANDARD  LVDS    } [get_ports    BANK14_M6_P     ]
# set_property -dict { PACKAGE_PIN    N6       IOSTANDARD  LVDS    } [get_ports    BANK14_N6_N     ]
# set_property -dict { PACKAGE_PIN    T7       IOSTANDARD  LVDS    } [get_ports    BANK14_T7_P     ]
# set_property -dict { PACKAGE_PIN    T8       IOSTANDARD  LVDS    } [get_ports    BANK14_T8_N     ]
# set_property -dict { PACKAGE_PIN    T9       IOSTANDARD  LVDS    } [get_ports    BANK14_T9_P     ]
# set_property -dict { PACKAGE_PIN    T10      IOSTANDARD  LVDS    } [get_ports    BANK14_T10_N     ]
# set_property -dict { PACKAGE_PIN    R5       IOSTANDARD  LVDS    } [get_ports    BANK14_R5_P     ]
# set_property -dict { PACKAGE_PIN    T5       IOSTANDARD  LVDS    } [get_ports    BANK14_T5_N     ]
# set_property -dict { PACKAGE_PIN    R6       IOSTANDARD  LVDS    } [get_ports    BANK14_R6_P     ]
# set_property -dict { PACKAGE_PIN    R7       IOSTANDARD  LVDS    } [get_ports    BANK14_R7_N     ]



# set_property -dict { PACKAGE_PIN    L4      IOSTANDARD  LVDS    } [get_ports    BANK34_L4_P      ]
# set_property -dict { PACKAGE_PIN    M4      IOSTANDARD  LVDS    } [get_ports    BANK34_M4_N      ]
# set_property -dict { PACKAGE_PIN    M2      IOSTANDARD  LVDS    } [get_ports    BANK34_M2_P     ]
# set_property -dict { PACKAGE_PIN    M1      IOSTANDARD  LVDS    } [get_ports    BANK34_M1_N     ]
# set_property -dict { PACKAGE_PIN    N3      IOSTANDARD  LVDS    } [get_ports    BANK34_N3_P     ]
# set_property -dict { PACKAGE_PIN    N2      IOSTANDARD  LVDS    } [get_ports    BANK34_N2_N     ]
# set_property -dict { PACKAGE_PIN    N1      IOSTANDARD  LVDS    } [get_ports    BANK34_N1_P     ]
# set_property -dict { PACKAGE_PIN    P1      IOSTANDARD  LVDS    } [get_ports    BANK34_P1_N     ]
# set_property -dict { PACKAGE_PIN    P4      IOSTANDARD  LVDS    } [get_ports    BANK34_P4_P     ]
# set_property -dict { PACKAGE_PIN    P3      IOSTANDARD  LVDS    } [get_ports    BANK34_P3_N     ]
# set_property -dict { PACKAGE_PIN    M5      IOSTANDARD  LVDS    } [get_ports    BANK34_M5_P     ]
# set_property -dict { PACKAGE_PIN    N4      IOSTANDARD  LVDS    } [get_ports    BANK34_N4_N     ]
# set_property -dict { PACKAGE_PIN    R2      IOSTANDARD  LVDS    } [get_ports    BANK34_R2_P     ]
# set_property -dict { PACKAGE_PIN    R1      IOSTANDARD  LVDS    } [get_ports    BANK34_R1_N     ]
# set_property -dict { PACKAGE_PIN    R3      IOSTANDARD  LVDS    } [get_ports    BANK34_R3_P     ]
# set_property -dict { PACKAGE_PIN    T2      IOSTANDARD  LVDS    } [get_ports    BANK34_T2_N     ]
# set_property -dict { PACKAGE_PIN    T4      IOSTANDARD  LVDS    } [get_ports    BANK34_T4_P     ]
# set_property -dict { PACKAGE_PIN    T3      IOSTANDARD  LVDS    } [get_ports    BANK34_T3_N     ]



# set_property -dict { PACKAGE_PIN    B7      IOSTANDARD  LVDS    } [get_ports    BANK35_B7_P     ]
# set_property -dict { PACKAGE_PIN    A7      IOSTANDARD  LVDS    } [get_ports    BANK35_A7_N     ]
# set_property -dict { PACKAGE_PIN    B6      IOSTANDARD  LVDS    } [get_ports    BANK35_B6_P     ]
# set_property -dict { PACKAGE_PIN    B5      IOSTANDARD  LVDS    } [get_ports    BANK35_B5_N     ]
# set_property -dict { PACKAGE_PIN    A5      IOSTANDARD  LVDS    } [get_ports    BANK35_A5_P     ]
# set_property -dict { PACKAGE_PIN    A4      IOSTANDARD  LVDS    } [get_ports    BANK35_A4_N     ]
# set_property -dict { PACKAGE_PIN    B4      IOSTANDARD  LVDS    } [get_ports    BANK35_B4_P     ]
# set_property -dict { PACKAGE_PIN    A3      IOSTANDARD  LVDS    } [get_ports    BANK35_A3_N     ]
# set_property -dict { PACKAGE_PIN    C7      IOSTANDARD  LVDS    } [get_ports    BANK35_C7_P     ]
# set_property -dict { PACKAGE_PIN    C6      IOSTANDARD  LVDS    } [get_ports    BANK35_C6_N     ]
# set_property -dict { PACKAGE_PIN    D6      IOSTANDARD  LVDS    } [get_ports    BANK35_D6_P     ]
# set_property -dict { PACKAGE_PIN    D5      IOSTANDARD  LVDS    } [get_ports    BANK35_D5_N     ]
# set_property -dict { PACKAGE_PIN    C3      IOSTANDARD  LVDS    } [get_ports    BANK35_C3_P     ]
# set_property -dict { PACKAGE_PIN    C2      IOSTANDARD  LVDS    } [get_ports    BANK35_C2_N     ]
# set_property -dict { PACKAGE_PIN    B2      IOSTANDARD  LVDS    } [get_ports    BANK35_B2_P     ]
# set_property -dict { PACKAGE_PIN    A2      IOSTANDARD  LVDS    } [get_ports    BANK35_A2_N     ]
# set_property -dict { PACKAGE_PIN    C1      IOSTANDARD  LVDS    } [get_ports    BANK35_C1_P     ]
# set_property -dict { PACKAGE_PIN    B1      IOSTANDARD  LVDS    } [get_ports    BANK35_B1_N     ]
# set_property -dict { PACKAGE_PIN    E2      IOSTANDARD  LVDS    } [get_ports    BANK35_E2_P     ]
# set_property -dict { PACKAGE_PIN    D1      IOSTANDARD  LVDS    } [get_ports    BANK35_D1_N     ]
# set_property -dict { PACKAGE_PIN    E3      IOSTANDARD  LVDS    } [get_ports    BANK35_E3_P     ]
# set_property -dict { PACKAGE_PIN    D3      IOSTANDARD  LVDS    } [get_ports    BANK35_D3_N     ]
# set_property -dict { PACKAGE_PIN    D4      IOSTANDARD  LVDS    } [get_ports    BANK35_D4_P     ]
# set_property -dict { PACKAGE_PIN    C4      IOSTANDARD  LVDS    } [get_ports    BANK35_C4_N     ]
# set_property -dict { PACKAGE_PIN    F5      IOSTANDARD  LVDS    } [get_ports    BANK35_F5_P     ]
# set_property -dict { PACKAGE_PIN    E5      IOSTANDARD  LVDS    } [get_ports    BANK35_E5_N     ]
# set_property -dict { PACKAGE_PIN    F4      IOSTANDARD  LVDS    } [get_ports    BANK35_F4_P     ]
# set_property -dict { PACKAGE_PIN    F3      IOSTANDARD  LVDS    } [get_ports    BANK35_F3_N     ]
# set_property -dict { PACKAGE_PIN    F2      IOSTANDARD  LVDS    } [get_ports    BANK35_F2_P     ]
# set_property -dict { PACKAGE_PIN    E1      IOSTANDARD  LVDS    } [get_ports    BANK35_E1_N     ]
# set_property -dict { PACKAGE_PIN    G5      IOSTANDARD  LVDS    } [get_ports    BANK35_G5_P     ]
# set_property -dict { PACKAGE_PIN    G4      IOSTANDARD  LVDS    } [get_ports    BANK35_G4_N     ]
# set_property -dict { PACKAGE_PIN    G2      IOSTANDARD  LVDS    } [get_ports    BANK35_G2_P     ]
# set_property -dict { PACKAGE_PIN    G1      IOSTANDARD  LVDS    } [get_ports    BANK35_G1_N     ]
# set_property -dict { PACKAGE_PIN    H5      IOSTANDARD  LVDS    } [get_ports    BANK35_H5_P     ]
# set_property -dict { PACKAGE_PIN    H4      IOSTANDARD  LVDS    } [get_ports    BANK35_H4_N     ]
# set_property -dict { PACKAGE_PIN    J5      IOSTANDARD  LVDS    } [get_ports    BANK35_J5_P     ]
# set_property -dict { PACKAGE_PIN    J4      IOSTANDARD  LVDS    } [get_ports    BANK35_J4_N     ]
# set_property -dict { PACKAGE_PIN    H2      IOSTANDARD  LVDS    } [get_ports    BANK35_H2_P     ]
# set_property -dict { PACKAGE_PIN    H1      IOSTANDARD  LVDS    } [get_ports    BANK35_H1_N     ]
# set_property -dict { PACKAGE_PIN    J3      IOSTANDARD  LVDS    } [get_ports    BANK35_J3_P     ]
# set_property -dict { PACKAGE_PIN    H3      IOSTANDARD  LVDS    } [get_ports    BANK35_H3_N     ]
# set_property -dict { PACKAGE_PIN    K1      IOSTANDARD  LVDS    } [get_ports    BANK35_K1_P     ]
# set_property -dict { PACKAGE_PIN    J1      IOSTANDARD  LVDS    } [get_ports    BANK35_J1_N     ]
# set_property -dict { PACKAGE_PIN    L3      IOSTANDARD  LVDS    } [get_ports    BANK35_L3_P     ]
# set_property -dict { PACKAGE_PIN    L2      IOSTANDARD  LVDS    } [get_ports    BANK35_L2_N     ]
# set_property -dict { PACKAGE_PIN    K3      IOSTANDARD  LVDS    } [get_ports    BANK35_K3_P     ]
# set_property -dict { PACKAGE_PIN    K2      IOSTANDARD  LVDS    } [get_ports    BANK35_K2_N     ]

