# SDRAM
set_property -dict { PACKAGE_PIN H12 IOSTANDARD LVCMOS33} [get_ports D0 ]
set_property -dict { PACKAGE_PIN H13 IOSTANDARD LVCMOS33} [get_ports D1 ]
set_property -dict { PACKAGE_PIN J15 IOSTANDARD LVCMOS33} [get_ports D2 ]
set_property -dict { PACKAGE_PIN H14 IOSTANDARD LVCMOS33} [get_ports D3 ]
set_property -dict { PACKAGE_PIN J16 IOSTANDARD LVCMOS33} [get_ports D4 ]
set_property -dict { PACKAGE_PIN H16 IOSTANDARD LVCMOS33} [get_ports D5 ]
set_property -dict { PACKAGE_PIN G14 IOSTANDARD LVCMOS33} [get_ports D6 ]
set_property -dict { PACKAGE_PIN G12 IOSTANDARD LVCMOS33} [get_ports D7 ]
set_property -dict { PACKAGE_PIN C16 IOSTANDARD LVCMOS33} [get_ports D8 ]
set_property -dict { PACKAGE_PIN D15 IOSTANDARD LVCMOS33} [get_ports D9 ]
set_property -dict { PACKAGE_PIN D16 IOSTANDARD LVCMOS33} [get_ports D10]
set_property -dict { PACKAGE_PIN E15 IOSTANDARD LVCMOS33} [get_ports D11]
set_property -dict { PACKAGE_PIN E16 IOSTANDARD LVCMOS33} [get_ports D12]
set_property -dict { PACKAGE_PIN F15 IOSTANDARD LVCMOS33} [get_ports D13]
set_property -dict { PACKAGE_PIN G15 IOSTANDARD LVCMOS33} [get_ports D14]
set_property -dict { PACKAGE_PIN G16 IOSTANDARD LVCMOS33} [get_ports D15]

set_property -dict { PACKAGE_PIN C13 IOSTANDARD LVCMOS33} [get_ports A0 ]
set_property -dict { PACKAGE_PIN A15 IOSTANDARD LVCMOS33} [get_ports A1 ]
set_property -dict { PACKAGE_PIN C12 IOSTANDARD LVCMOS33} [get_ports A2 ]
set_property -dict { PACKAGE_PIN C11 IOSTANDARD LVCMOS33} [get_ports A3 ]
set_property -dict { PACKAGE_PIN A9  IOSTANDARD LVCMOS33} [get_ports A4 ]
set_property -dict { PACKAGE_PIN B9  IOSTANDARD LVCMOS33} [get_ports A5 ]
set_property -dict { PACKAGE_PIN A10 IOSTANDARD LVCMOS33} [get_ports A6 ]
set_property -dict { PACKAGE_PIN B10 IOSTANDARD LVCMOS33} [get_ports A7 ]
set_property -dict { PACKAGE_PIN B11 IOSTANDARD LVCMOS33} [get_ports A8 ]
set_property -dict { PACKAGE_PIN A12 IOSTANDARD LVCMOS33} [get_ports A9 ]
set_property -dict { PACKAGE_PIN B15 IOSTANDARD LVCMOS33} [get_ports A10]
set_property -dict { PACKAGE_PIN B12 IOSTANDARD LVCMOS33} [get_ports A11]
set_property -dict { PACKAGE_PIN A13 IOSTANDARD LVCMOS33} [get_ports A12]
set_property -dict { PACKAGE_PIN D13 IOSTANDARD LVCMOS33} [get_ports A13]
set_property -dict { PACKAGE_PIN C14 IOSTANDARD LVCMOS33} [get_ports A14]

set_property -dict { PACKAGE_PIN A14 IOSTANDARD LVCMOS33} [get_ports SDCKE0 ]
set_property -dict { PACKAGE_PIN B14 IOSTANDARD LVCMOS33} [get_ports SDCLK0 ]
set_property -dict { PACKAGE_PIN F12 IOSTANDARD LVCMOS33} [get_ports DQML   ]
set_property -dict { PACKAGE_PIN B16 IOSTANDARD LVCMOS33} [get_ports DQMH   ]
set_property -dict { PACKAGE_PIN F13 IOSTANDARD LVCMOS33} [get_ports CAS    ]
set_property -dict { PACKAGE_PIN E13 IOSTANDARD LVCMOS33} [get_ports RAS    ]
set_property -dict { PACKAGE_PIN F14 IOSTANDARD LVCMOS33} [get_ports SDWE   ]
set_property -dict { PACKAGE_PIN D14 IOSTANDARD LVCMOS33} [get_ports SD_NCS0]